export enum PRIVILEGE {
  LIST_WAREHOUSE = 'LIST_WAREHOUSE',
  DELETE_WAREHOUSE = 'DELETE_WAREHOUSE',
  DETAIL_WAREHOUSE = 'DETAIL_WAREHOUSE',
  EDIT_WAREHOUSE = 'EDIT_WAREHOUSE',
  CREATE_WAREHOUSE = 'CREATE_WAREHOUSE',
  SETTING_PRIVILEGE = 'SETTING_PRIVILEGE',
}
